### ISSUE TITLE
Redesign Spurri Logo

### ISSUE THREAD

**Issue by seanauriti** [Spurri/website#120]
![image](https://cloud.githubusercontent.com/assets/7475382/22399316/ecf23f60-e567-11e6-9ec7-445cd12f6b9b.png)

This is an inspiration for the logo.  The logo should look industrial with a machine looking font, and have a gear that represents spurs potentially with a metallic look.

**Comment by mareiska** [comment]
Please give me feedback to incorporate into a design more to your liking
![spurri](https://cloud.githubusercontent.com/assets/16075543/22401693/43b3ced4-e5ab-11e6-81be-f4ff7695af4c.png)

**Comment by seanauriti** [comment]
New logo looks great!
![image](https://cloud.githubusercontent.com/assets/7475382/24123219/0807178a-0d95-11e7-8e53-8f7e80d800a6.png)
