### ISSUE TITLE
Building a test Spurri site

### ISSUE THREAD

**Issue by cryptotym** [Spurri/website#178]
Hi, I love the framework of Spurri, it has spurred ;) me to build a test version on my local machine. I run:
pipenv install
pipenv shell
manage.py migrate

Then I get an error that says 
"django.db.utils.OperationalError: no such table: django_content_type"
Do you know how I can create the tables necessary to run the site?
Also I tried this on the local machine and Heroku, but both seem to not work. Any help would be appreciated. Thanks and great  job on the site!!

**Comment by fredfalcon** [comment]
make sure sqlite is installed by running sqlite from the command line.

**Comment by cryptotym** [comment]
Verified it wouldn't run from the cmd line. Now I've installed sqlite3 and added it to path, but still the pipfile doesn't write the database. I tried renaming the sqlite3.exe as sqlite(since you referenced that above), but still doesn't work.

Could this be because I'm using 64bit windows? I do get an error during pipenv install 
"Ignoring pylibmc: markers 'sys_platform != "win32"' don't match your environment"
After it seems to work because it says to run pipenv shell and on Ubuntu I haven't even got that far.

I feel like I'm getting so close!

**Comment by fredfalcon** [comment]
python manage.py migrate 
that will write the database.  If you can run pipenv shell and there are no errors, you are mostly done other than the database.

**Comment by cryptotym** [comment]
The error occurs after inside the pipenv shell after running python manage.py migrate..

I just tested it again and confirmed it is still happening.

I'm gonna close this for now, I no longer have time to troubleshoot :( Thanks for all you help!

**Comment by fredfalcon** [comment]
sure, another suggestion is to try deleting the db.sqlite3 file and running migrate again.
