### ISSUE TITLE
When user submits the signup form without any data, the first Mandatory field is highlighted but the Error message pop up is dislocated.

### ISSUE THREAD

**Issue by seanauriti** [Spurri/website#88]
![0](https://bhfiles.storage.googleapis.com/screenshots/Spurri-Defect_1.png) http://bugheist.com/issue/184

**Comment by gisete** [comment]
Hi. I took a look at the website and cannot recreate  the issue. Tested on a Mac Chrome Version 61.0.3 and Firefox 55.0.3. I see you are on Windows and using Chrome, can you share your browser version? Thanks.

**Comment by seanauriti** [comment]
Thanks for taking a look, I've confirmed this works fine and will close it.
